export const Words = [
    {
        id: 0,
        img: 'acorn',
        primary_meaning: 'acorn',
        additional_meanings: '',
        hiragana: 'どんぐり',
        kanji: '団栗',
        romaji: 'donguri',
        kunyomi: '',
        onyomi: '',
        category: "nature", 
        type: "noun",
        example: "百合さんは団栗を食べます。"
    },
    {
        id: 1,
        img: 'plane',
        primary_meaning: 'plane',
        additional_meanings: '',
        hiragana: 'ひこうき',
        kanji: '飛行機',
        romaji: 'hikouki',
        kunyomi: '',
        onyomi: '',
        category: "travel",
        type: "noun",
        example: "飛行機で日本に行きました。"
    },
    {
        id: 2,
        img: 'person',
        primary_meaning: 'person',
        additional_meanings: '',
        hiragana: 'ひと',
        kanji: '人',
        romaji: 'hito',
        kunyomi: '',
        onyomi: '',
        category: "people",
        type: "noun",
        example: "あの人は私の友達です。"
    },
    {
        id: 3,
        img:  '',
        primary_meaning:  'name',
        additional_meanings: '',
        hiragana:  'なまえ',
        kanji: '名前',
        romaji: 'namae',
        kunyomi: '',
        onyomi: '',
        category: 'noun',
        type: 'noun',
        example: 'これ人の名前はさくらです。'
    },
    {
        id: 4,
        img:  '',
        primary_meaning:  'Hello',
        additional_meanings: 'Good afternoon',
        hiragana:  'こんにちわ',
        kanji: 'こんにちわ',
        romaji: 'konnichiwa',
        kunyomi: '',
        onyomi: '',
        category: 'greeting',
        type: 'exclamation',
        example: ''
    },
    {
        id: 5,
        img:  '',
        primary_meaning:  'Good morning',
        additional_meanings: '',
        hiragana:  'おはよう',
        kanji: 'おはよう',
        romaji: 'ohayo',
        kunyomi: '',
        onyomi: '',
        category: 'greeting',
        type: 'exclamation',
        example: ''
    },
    {
        id: 6,
        img:  '',
        primary_meaning:  'Thank you',
        additional_meanings: '',
        hiragana:  'ありがとう',
        kanji: 'ありがとう',
        romaji: 'arigatou',
        kunyomi: '',
        onyomi: '',
        category: 'gratitude',
        type: 'exclamation',
        example: ''
    },
    {
        id: 7,
        img:  '',
        primary_meaning:  'To drink',
        additional_meanings: '',
        hiragana:  'のむ',
        kanji: '飲む',
        romaji: 'nomu',
        kunyomi: '',
        onyomi: '',
        category: 'verb',
        type: 'verb',
        example: '水を飲みます。'
    },
    {
        id: 8,
        img:  '',
        primary_meaning:  'To eat',
        additional_meanings: '',
        hiragana:  'たべる',
        kanji: '食べる',
        romaji: 'taberu',
        kunyomi: '',
        onyomi: '',
        category: 'verb',
        type: 'verb',
        example: 'ご飯をたべます。'
    },
    {
        id: 9,
        img:  '',
        primary_meaning:  'To see',
        additional_meanings: '',
        hiragana:  'みる',
        kanji: '見る',
        romaji: 'miru',
        kunyomi: '',
        onyomi: '',
        category: 'verb',
        type: 'verb',
        example: 'さくらはフクロウを見た'
    },
    {
        id: 10,
        img:  '',
        primary_meaning:  'To talk',
        additional_meanings: '',
        hiragana:  'はなす',
        kanji: '話す',
        romaji: 'hanasu',
        kunyomi: '',
        onyomi: '',
        category: 'verb',
        type: 'verb',
        example: '英語を話すことができる'
    },
    {
        id: 11,
        img:  '',
        primary_meaning:  'To go',
        additional_meanings: '',
        hiragana:  'いく',
        kanji: '行く',
        romaji: 'iku',
        kunyomi: '',
        onyomi: '',
        category: 'verb',
        type: 'verb',
        example: '店に行った。'
    },
    {
        id: 12,
        img:  '',
        primary_meaning:  'To Do',
        additional_meanings: '',
        hiragana:  'する',
        kanji: 'する',
        romaji: 'suru',
        kunyomi: '',
        onyomi: '',
        category: 'verb',
        type: 'verb',
        example: 'テレビの音を大きくした。'
    },
    {
        id: 13,
        img:  '',
        primary_meaning:  'Picture',
        additional_meanings: '',
        hiragana:  'しゃしん',
        kanji: '写真',
        romaji: 'shashin',
        kunyomi: '',
        onyomi: '',
        category: 'Photography',
        type: 'noun',
        example: 'いい写真ですね。'
    },
    {
        id: 14,
        img:  '',
        primary_meaning:  'Station',
        additional_meanings: '',
        hiragana:  'えき',
        kanji: '駅',
        romaji: 'eki',
        kunyomi: '',
        onyomi: '',
        category: 'Travel',
        type: 'noun',
        example: '駅前で会いましょう。'
    },
    {
        id: 15,
        img:  '',
        primary_meaning:  'Tomorrow',
        additional_meanings: '',
        hiragana:  'あした',
        kanji: '明日',
        romaji: 'ashita',
        kunyomi: '',
        onyomi: '',
        category: 'Time',
        type: 'Noun',
        example: '明日日本に行きます。'
    },
    {
        id: 16,
        img:  '',
        primary_meaning:  'Today',
        additional_meanings: '',
        hiragana:  'きょう',
        kanji: '今日',
        romaji: 'kyou',
        kunyomi: '',
        onyomi: '',
        category: 'Time',
        type: 'noun',
        example: '今日は宿題をします'
    },
    {
        id: 17,
        img:  '',
        primary_meaning:  'Yesterday',
        additional_meanings: '',
        hiragana:  'きのう',
        kanji: '昨日',
        romaji: 'kinou',
        kunyomi: '',
        onyomi: '',
        category: 'Time',
        type: 'noun',
        example: '昨日私は映画を見ます'
    },
    {
        id: 18,
        img:  '',
        primary_meaning:  'Room',
        additional_meanings: '',
        hiragana:  'へや',
        kanji: '部屋',
        romaji: 'heya',
        kunyomi: '',
        onyomi: '',
        category: 'Location',
        type: 'Noun',
        example: 'さくらさん、部屋を掃除してください'
    },
    {
        id: 19,
        img:  '',
        primary_meaning:  'School',
        additional_meanings: '',
        hiragana:  'がっこう',
        kanji: '学校',
        romaji: 'gakkou',
        kunyomi: '',
        onyomi: '',
        category: 'Education',
        type: 'Noun',
        example: 'さくらは学校に行くのが好きです。'
    },
    {
        id: 20,
        img:  '',
        primary_meaning:  'Word',
        additional_meanings: '',
        hiragana:  'ことば',
        kanji: '言葉',
        romaji: 'kotoba',
        kunyomi: '',
        onyomi: '',
        category: 'Literature',
        type: 'Noun',
        example: '辞書にはたくさんの言葉が載っている。'
    },
    {
        id: 21,
        img:  '',
        primary_meaning:  'Water',
        additional_meanings: '',
        hiragana:  'みず',
        kanji: '水',
        romaji: 'mizu',
        kunyomi: '',
        onyomi: '',
        category: 'Nature',
        type: 'Noun',
        example: '海岸の水はきれいです。'
    },
    {
        id: 22,
        img:  '',
        primary_meaning:  'Store',
        additional_meanings: '',
        hiragana:  'みせ',
        kanji: '店',
        romaji: 'mise',
        kunyomi: '',
        onyomi: '',
        category: 'Location',
        type: 'Noun',
        example: 'この店のラーメンは美味しいです.'
    },
    {
        id: 23,
        img:  '',
        primary_meaning:  'Japanese Restaurant',
        additional_meanings: '',
        hiragana:  'おしょくじどころ',
        kanji: 'お食事処',
        romaji: 'Oshokujidokoro',
        kunyomi: '',
        onyomi: '',
        category: 'Location',
        type: 'noun',
        example: 'お食事処に行きましょう'
    },
    {
        id: 24,
        img:  '',
        primary_meaning:  'Library',
        additional_meanings: '',
        hiragana:  'としょかん',
        kanji: '図書館',
        romaji: 'Toshokan',
        kunyomi: '',
        onyomi: '',
        category: 'Location',
        type: 'Noun',
        example: '図書館で本を借りました.'
    },
    {
        id: 25,
        img:  '',
        primary_meaning:  'Home',
        additional_meanings: '',
        hiragana:  'いえ',
        kanji: '家',
        romaji: 'ie',
        kunyomi: '',
        onyomi: '',
        category: 'Location',
        type: 'Noun',
        example: 'さくらさんは家に帰りました。'
    },
    
    
]

export default {
  Words,
}